spring:
  config:
    activate:
      on-profile: test
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: 'NOT_USE_OAUTH2_TEST'
            client-secret: 'NOT_USE_OAUTH2_TEST'
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user-name-attribute: response
  mail:
    host: smtp.naver.com
    port: 587
    username: 'NOT_USE_MAIL_TEST'
    password: 'NOT_USE_MAIL_TEST'
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    show-sql: true
  jwt:
    secret: 'ONLY_TEST_PROFILE_JWT_TOKEN_SECRET_KEY'
    access:
      expiredTime: 6000
    refresh:
      expiredTime: 360000
  data:
    redis:
      host: 'localhost'
      port: 64588
      password: redisdb@1234